### ISSUE TITLE
Week1での質問

### ISSUE THREAD

**Issue by kazdevl** [chatbox-inc/saito_kadai#5]
#3 にあるDB定義で良いのかどうか

**Comment by kazdevl** [comment]
slackAppのscopeは、user:readとincoming-webhookのみ追加しているが、
他にも追加すべきscopeはあるのかどうか

**Comment by kazdevl** [comment]
Laravelの環境変数に入れたのは、SLACK_URLと、SLACK_TOKENのみで良いのか

**Comment by mikakane** [comment]
> slackAppのscopeは、user:readとincoming-webhookのみ追加しているが、
> 他にも追加すべきscopeはあるのかどうか

これ、多分実装しながら追加していく感じ Slack Token からの応答時に認証エラーにならない形で

**Comment by mikakane** [comment]
> #3 にあるDB定義で良いのかどうか

これは、一旦 マイグレーションファイルの形式で PR ください。読みにくい！
